greet function
adzai/chatbot pull request #37
Opened 2020-11-15 19:57 UTC by AniSanikidze

The greet function checks whether the user input is greeting or not. Based on the result of similarity function, retrievs random greeting message from vector of responses and prints it or returns true value.

2020-11-15 22:50 UTC, adzai reviewed
Seems nice, could you add a test for it?

2020-11-16 08:12 UTC, AniSanikidze commented
> Seems nice, could you add a test for it?

Yeah, I added.

2020-11-16 12:32 UTC, adzai requested changes

2020-11-16 12:32 UTC, adzai commented on src/chatbot/greet.clj
> +  "Using similarity function, identifies if the user-input is in possible-greetings, if true function prints random greeting message, otherwise retruns true."
> if true function prints random greeting message, otherwise retruns true.

See that this is a problem? If true it prints, if false it returns true. So it should return false, right?

2020-11-16 12:32 UTC, adzai commented on src/chatbot/greet.clj
> +             (println (rand-nth responses))
I think we should reserve printing for the main loop, these helper functions should always return something useful. So I would just return a string which is the response, or false if it didn't find anything. It will help with the testing as well.

2020-11-16 12:35 UTC, AniSanikidze commented on src/chatbot/greet.clj
> +  "Using similarity function, identifies if the user-input is in possible-greetings, if true function prints random greeting message, otherwise retruns true."
Yeah, definitely, returning true when the expression is false is illogical. I'll change it here as well.

2020-11-16 12:38 UTC, AniSanikidze commented on src/chatbot/greet.clj
> +             (println (rand-nth responses))
I don't quite understand what you mean by returning "a string which is the response".  Do you mean to remove println and just leave (rand-nth responses)?

2020-11-16 12:49 UTC, adzai commented on src/chatbot/greet.clj
> +             (println (rand-nth responses))
Yes. And since the response is random, you can probably make a test which verifies that the response comes from the response vector or returns false if a greeting doesn't apply.

Also, I see that you can remove the do statement (the let scope should cover for it)

2020-11-16 12:51 UTC, AniSanikidze commented on src/chatbot/greet.clj
> +             (println (rand-nth responses))
Okay, thank you for clarification.

2020-11-16 13:31 UTC, adzai commented on test/chatbot/core_test.clj
> +(deftest greeting-test
Can you also add a test where it returns a greeting?

2020-11-16 13:33 UTC, AniSanikidze commented on test/chatbot/core_test.clj
> +(deftest greeting-test
Sure.

2020-11-16 14:07 UTC, adzai commented on test/chatbot/core_test.clj
> +         (contains? responses (greeting possible-greetings "hi"))))))
Probably want to use [this](https://clojuredocs.org/clojure.core/some#example-542692c6c026201cdc32693d)

2020-11-17 11:29 UTC, adzai commented on src/chatbot/greet.clj
> +  "Using similarity function, identifies if the user-input is in possible-greetings, if true function prints random greeting message, otherwise retruns true."
https://guide.clojure.style/#line-length

2020-11-17 12:57 UTC, adzai submitted a review, later dismissed
Looks good to me, nice work!

2020-11-19 16:55 UTC, irinakulinich3712 submitted a review, later dismissed
Nice work!

2020-11-20 10:19 UTC, adzai approved these changes

2020-11-21 14:04 UTC, irinakulinich3712 approved these changes

2020-11-21 14:10 UTC, merged